import { AwsClient } from "aws4fetch";
import type { MediaAsset } from "@/db";

// Neon Object Storage (S3-compatible), private "library" bucket. Credentials come from `neon env pull`
// (AWS_ACCESS_KEY_ID, AWS_SECRET_ACCESS_KEY, AWS_ENDPOINT_URL_S3, AWS_REGION). Each Neon branch has its own bucket
// contents, so dev uploads never reach production. Browsers only ever get short-lived signed links.

const BUCKET = "library";
const LINK_SECONDS = 300;

export const MAX_UPLOAD_BYTES = 500 * 1024 * 1024;

let client: AwsClient | null = null;

export function isStorageConfigured(): boolean {
  const { AWS_ACCESS_KEY_ID, AWS_SECRET_ACCESS_KEY, AWS_ENDPOINT_URL_S3, AWS_REGION } = process.env;
  return Boolean(AWS_ACCESS_KEY_ID && AWS_SECRET_ACCESS_KEY && AWS_ENDPOINT_URL_S3 && AWS_REGION);
}

function aws(): AwsClient {
  client ??= new AwsClient({
    accessKeyId: process.env.AWS_ACCESS_KEY_ID!,
    secretAccessKey: process.env.AWS_SECRET_ACCESS_KEY!,
    region: process.env.AWS_REGION!,
    service: "s3",
  });
  return client;
}

// Path-style URL. Keys are generated by the server (see newObjectKey), so they never need escaping beyond this.
const objectUrl = (key: string) =>
  new URL(`${process.env.AWS_ENDPOINT_URL_S3!.replace(/\/$/, "")}/${BUCKET}/${key.split("/").map(encodeURIComponent).join("/")}`);

async function presign(url: URL, method: "GET" | "PUT"): Promise<string> {
  url.searchParams.set("X-Amz-Expires", String(LINK_SECONDS));
  return (await aws().sign(url.toString(), { method, aws: { signQuery: true } })).url;
}

export const KEY_PATTERN = /^uploads\/\d{4}\/[a-f0-9]{16}\/[A-Za-z0-9._-]{1,120}$/;

/** A fresh, unguessable object key that keeps a readable version of the file name. */
export function newObjectKey(filename: string): string {
  const safe = filename.replace(/[^A-Za-z0-9._-]+/g, "-").replace(/^[-.]+/, "").slice(-120) || "file";
  const rand = Array.from(globalThis.crypto.getRandomValues(new Uint8Array(8)), (b) => b.toString(16).padStart(2, "0")).join("");
  return `uploads/${new Date().getUTCFullYear()}/${rand}/${safe}`;
}

/** A browser-reported MIME type, or application/octet-stream when it is missing or malformed. */
export function cleanMime(value: unknown): string {
  return typeof value === "string" && value.length <= 120 && /^[\w.+-]+\/[\w.+-]+$/.test(value) ? value.toLowerCase() : "application/octet-stream";
}

/** Shows the original file name on download. ASCII fallback plus the UTF-8 form (RFC 6266). */
export function contentDisposition(filename: string): string {
  const ascii = filename.replace(/[^\x20-\x7e]|["\\]/g, "_");
  return `inline; filename="${ascii}"; filename*=UTF-8''${encodeURIComponent(filename)}`;
}

// Uploads are multipart: the browser sends the file straight to storage in PART_BYTES pieces, each through its own
// signed link. A single long PUT is cut off by storage after about 10 minutes, which a slow connection reaches well
// before the size cap. Only the last part may be smaller than 5 MiB (S3 rule).
export const PART_BYTES = 16 * 1024 * 1024;
export const MAX_PARTS = Math.ceil(MAX_UPLOAD_BYTES / PART_BYTES);
export const UPLOAD_ID_PATTERN = /^[A-Za-z0-9._~+/=-]{1,256}$/;

const uploadIdUrl = (key: string, uploadId: string) => {
  const url = objectUrl(key);
  url.searchParams.set("uploadId", uploadId);
  return url;
};

/**
 * Starts a multipart upload and returns its id. Neon storage ignores per-link response overrides, so the original
 * file name is stored with the object here.
 */
export async function startUpload(key: string, filename: string, mime: string): Promise<string> {
  const url = objectUrl(key);
  url.search = "uploads";
  const res = await aws().fetch(url.toString(), {
    method: "POST",
    headers: { "content-disposition": contentDisposition(filename), "content-type": mime },
  });
  const uploadId = (await res.text()).match(/<UploadId>([^<]+)<\/UploadId>/)?.[1];
  if (!res.ok || !uploadId) throw new Error(`Storage multipart start failed: ${res.status}`);
  return uploadId;
}

/** Signed PUT for one part (1-based). Expiry is checked when the part starts, so slow parts still finish. */
export function partUrl(key: string, uploadId: string, partNumber: number): Promise<string> {
  const url = uploadIdUrl(key, uploadId);
  url.searchParams.set("partNumber", String(partNumber));
  return presign(url, "PUT");
}

/**
 * Joins the uploaded parts into the object. The part list (with ETags) is read from storage, because storage does not
 * expose ETag to browsers. Returns false when the upload is unknown or incomplete.
 */
export async function completeUpload(key: string, uploadId: string): Promise<boolean> {
  const list = await aws().fetch(uploadIdUrl(key, uploadId).toString());
  if (list.status === 404) return false;
  if (!list.ok) throw new Error(`Storage ListParts failed: ${list.status}`);
  // At most MAX_PARTS (32) parts, so the first page of 1,000 is the whole list.
  const parts = [...(await list.text()).matchAll(/<Part>[\s\S]*?<PartNumber>(\d+)<\/PartNumber>[\s\S]*?<ETag>([^<]+)<\/ETag>[\s\S]*?<\/Part>/g)];
  if (parts.length === 0) return false;
  // ETags arrive XML-escaped and go back into XML unchanged.
  const body = `<CompleteMultipartUpload>${parts.map(([, n, etag]) => `<Part><PartNumber>${n}</PartNumber><ETag>${etag}</ETag></Part>`).join("")}</CompleteMultipartUpload>`;
  const res = await aws().fetch(uploadIdUrl(key, uploadId).toString(), { method: "POST", body });
  const text = await res.text();
  // S3 can report a failed complete inside a 200 response.
  if (res.status >= 500 || (res.ok && text.includes("<Error>"))) throw new Error(`Storage multipart complete failed: ${res.status}`);
  return res.ok;
}

/** Throws away an unfinished upload and its parts. Unknown uploads succeed, so retries are safe. */
export async function abortUpload(key: string, uploadId: string): Promise<void> {
  const res = await aws().fetch(uploadIdUrl(key, uploadId).toString(), { method: "DELETE" });
  if (!res.ok && res.status !== 404) throw new Error(`Storage multipart abort failed: ${res.status}`);
}

/** Signed GET, valid for 5 minutes. */
export const downloadUrl = (key: string) => presign(objectUrl(key), "GET");

/** Size in bytes of a stored object, or null when it does not exist. */
export async function objectSize(key: string): Promise<number | null> {
  const res = await aws().fetch(objectUrl(key).toString(), { method: "HEAD" });
  if (res.status === 404) return null;
  if (!res.ok) throw new Error(`Storage HEAD failed: ${res.status}`);
  return Number(res.headers.get("content-length") ?? 0);
}

/** Deletes an object. Deleting a missing object succeeds, so retries are safe. */
export async function deleteObject(key: string): Promise<void> {
  const res = await aws().fetch(objectUrl(key).toString(), { method: "DELETE" });
  if (!res.ok && res.status !== 404) throw new Error(`Storage DELETE failed: ${res.status}`);
}

const xmlValue = (block: string, tag: string) => block.match(new RegExp(`<${tag}>([^<]*)</${tag}>`))?.[1];

/**
 * Leftovers of uploads that never made it into the Library, older than `before`: unfinished multipart uploads (tab
 * closed mid-upload) and stored objects (tab closed before registering; the caller checks them against media_assets).
 * Only keys the app generates are returned, so nothing else in the bucket is ever touched.
 */
export async function findStaleUploads(before: Date): Promise<{ unfinished: { key: string; uploadId: string }[]; objects: string[] }> {
  const base = objectUrl("x");
  base.pathname = `/${BUCKET}`;
  const unfinished: { key: string; uploadId: string }[] = [];
  const objects: string[] = [];

  for (let markers = "", more = true; more; ) {
    const res = await aws().fetch(`${base}?uploads&prefix=uploads/${markers}`);
    if (!res.ok) throw new Error(`Storage ListMultipartUploads failed: ${res.status}`);
    const xml = await res.text();
    for (const [block] of xml.matchAll(/<Upload>[\s\S]*?<\/Upload>/g)) {
      const key = xmlValue(block, "Key") ?? "";
      const uploadId = xmlValue(block, "UploadId") ?? "";
      if (KEY_PATTERN.test(key) && new Date(xmlValue(block, "Initiated") ?? "") < before) unfinished.push({ key, uploadId });
    }
    more = xmlValue(xml, "IsTruncated") === "true";
    markers = `&key-marker=${encodeURIComponent(xmlValue(xml, "NextKeyMarker") ?? "")}&upload-id-marker=${encodeURIComponent(xmlValue(xml, "NextUploadIdMarker") ?? "")}`;
  }

  for (let token = "", more = true; more; ) {
    const res = await aws().fetch(`${base}?list-type=2&prefix=uploads/${token}`);
    if (!res.ok) throw new Error(`Storage ListObjectsV2 failed: ${res.status}`);
    const xml = await res.text();
    for (const [block] of xml.matchAll(/<Contents>[\s\S]*?<\/Contents>/g)) {
      const key = xmlValue(block, "Key") ?? "";
      if (KEY_PATTERN.test(key) && new Date(xmlValue(block, "LastModified") ?? "") < before) objects.push(key);
    }
    more = xmlValue(xml, "IsTruncated") === "true";
    token = `&continuation-token=${encodeURIComponent(xmlValue(xml, "NextContinuationToken") ?? "")}`;
  }
  return { unfinished, objects };
}

export function formatSize(bytes: number): string {
  if (bytes < 1024) return `${bytes} B`;
  const units = ["KB", "MB", "GB"];
  let n = bytes / 1024;
  let i = 0;
  while (n >= 1024 && i < units.length - 1) {
    n /= 1024;
    i++;
  }
  return `${n.toFixed(n < 10 ? 1 : 0)} ${units[i]}`;
}

export function fileTypeFor(mime: string): MediaAsset["fileType"] {
  const top = mime.split("/")[0];
  return top === "image" || top === "video" || top === "audio" ? top : "document";
}
