import { AwsClient } from "aws4fetch";
import type { MediaAsset } from "@/db";

// Neon Object Storage (S3-compatible), private "library" bucket. Credentials come from `neon env pull`
// (AWS_ACCESS_KEY_ID, AWS_SECRET_ACCESS_KEY, AWS_ENDPOINT_URL_S3, AWS_REGION). Each Neon branch has its own bucket
// contents, so dev uploads never reach production. Browsers only ever get short-lived signed links.

const BUCKET = "library";
const LINK_SECONDS = 300;

export const MAX_UPLOAD_BYTES = 500 * 1024 * 1024;

let client: AwsClient | null = null;

export function isStorageConfigured(): boolean {
  const { AWS_ACCESS_KEY_ID, AWS_SECRET_ACCESS_KEY, AWS_ENDPOINT_URL_S3, AWS_REGION } = process.env;
  return Boolean(AWS_ACCESS_KEY_ID && AWS_SECRET_ACCESS_KEY && AWS_ENDPOINT_URL_S3 && AWS_REGION);
}

function aws(): AwsClient {
  client ??= new AwsClient({
    accessKeyId: process.env.AWS_ACCESS_KEY_ID!,
    secretAccessKey: process.env.AWS_SECRET_ACCESS_KEY!,
    region: process.env.AWS_REGION!,
    service: "s3",
  });
  return client;
}

// Path-style URL. Keys are generated by the server (see newObjectKey), so they never need escaping beyond this.
const objectUrl = (key: string) =>
  new URL(`${process.env.AWS_ENDPOINT_URL_S3!.replace(/\/$/, "")}/${BUCKET}/${key.split("/").map(encodeURIComponent).join("/")}`);

async function presign(url: URL, method: "GET" | "PUT", headers?: Record<string, string>): Promise<string> {
  url.searchParams.set("X-Amz-Expires", String(LINK_SECONDS));
  return (await aws().sign(url.toString(), { method, headers, aws: { signQuery: true } })).url;
}

export const KEY_PATTERN = /^uploads\/\d{4}\/[a-f0-9]{16}\/[A-Za-z0-9._-]{1,120}$/;

/** A fresh, unguessable object key that keeps a readable version of the file name. */
export function newObjectKey(filename: string): string {
  const safe = filename.replace(/[^A-Za-z0-9._-]+/g, "-").replace(/^[-.]+/, "").slice(-120) || "file";
  const rand = Array.from(globalThis.crypto.getRandomValues(new Uint8Array(8)), (b) => b.toString(16).padStart(2, "0")).join("");
  return `uploads/${new Date().getUTCFullYear()}/${rand}/${safe}`;
}

/** Shows the original file name on download. ASCII fallback plus the UTF-8 form (RFC 6266). */
export function contentDisposition(filename: string): string {
  const ascii = filename.replace(/[^\x20-\x7e]|["\\]/g, "_");
  return `inline; filename="${ascii}"; filename*=UTF-8''${encodeURIComponent(filename)}`;
}

/**
 * Signed PUT the browser uploads to directly, so large files never pass through the app server. The browser must send
 * `headers` unchanged (they are part of the signature). Neon storage ignores per-link response overrides, so the file
 * name is stored with the object here.
 */
export async function uploadUrl(key: string, filename: string): Promise<{ url: string; headers: Record<string, string> }> {
  const headers = { "content-disposition": contentDisposition(filename) };
  return { url: await presign(objectUrl(key), "PUT", headers), headers };
}

/** Signed GET, valid for 5 minutes. */
export const downloadUrl = (key: string) => presign(objectUrl(key), "GET");

/** Size in bytes of a stored object, or null when it does not exist. */
export async function objectSize(key: string): Promise<number | null> {
  const res = await aws().fetch(objectUrl(key).toString(), { method: "HEAD" });
  if (res.status === 404) return null;
  if (!res.ok) throw new Error(`Storage HEAD failed: ${res.status}`);
  return Number(res.headers.get("content-length") ?? 0);
}

/** Deletes an object. Deleting a missing object succeeds, so retries are safe. */
export async function deleteObject(key: string): Promise<void> {
  const res = await aws().fetch(objectUrl(key).toString(), { method: "DELETE" });
  if (!res.ok && res.status !== 404) throw new Error(`Storage DELETE failed: ${res.status}`);
}

export function formatSize(bytes: number): string {
  if (bytes < 1024) return `${bytes} B`;
  const units = ["KB", "MB", "GB"];
  let n = bytes / 1024;
  let i = 0;
  while (n >= 1024 && i < units.length - 1) {
    n /= 1024;
    i++;
  }
  return `${n.toFixed(n < 10 ? 1 : 0)} ${units[i]}`;
}

export function fileTypeFor(mime: string): MediaAsset["fileType"] {
  const top = mime.split("/")[0];
  return top === "image" || top === "video" || top === "audio" ? top : "document";
}
